### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by abejfehr** [Rudolph-Miller/react-sortable-table#4]
This is the output I receive:

    Abrams-MacBook-Pro:SomeRepo abejfehr$ npm install react-sortable-table
    npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
    npm WARN prefer global react-tools@0.13.3 should be installed with -g

    > react-sortable-table@0.1.0 install /some/dir/node_modules/react-sortable-table
    > node_modules/react-tools/bin/jsx --extension jsx --no-cache-dir src/ js/

    sh: node_modules/react-tools/bin/jsx: No such file or directory
    - acorn-globals node_modules/formsy-react/node_modules/acorn-globals
    - escodegen node_modules/formsy-react/node_modules/escodegen
    - fsevents node_modules/formsy-react/node_modules/fsevents
    - node-pre-gyp node_modules/formsy-react/node_modules/fsevents/node_modules/node-pre-gyp
    - tar-pack node_modules/formsy-react/node_modules/fsevents/node_modules/tar-pack
    - jsdom node_modules/formsy-react/node_modules/jsdom
    - jstransform node_modules/formsy-react/node_modules/jstransform
    - regexpu node_modules/formsy-react/node_modules/regexpu
    - webpack node_modules/formsy-react/node_modules/webpack
    /some/dir
    ├── ajacks@1.0.0 
    ├── dateformat@1.0.12 
    ├── react-modal@0.6.1  extraneous
    └── react-tools@0.13.3 

    npm WARN vueify@5.0.4 requires a peer of vue-hot-reload-api@^1.2.0 but none was installed.
    npm WARN vueify@5.0.4 requires a peer of vueify-insert-css@^1.0.0 but none was installed.
    npm ERR! Darwin 15.2.0
    npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install" "react-sortable-table"
    npm ERR! node v5.3.0
    npm ERR! npm  v3.5.3
    npm ERR! file sh
    npm ERR! code ELIFECYCLE
    npm ERR! errno ENOENT
    npm ERR! syscall spawn

    npm ERR! react-sortable-table@0.1.0 install: `node_modules/react-tools/bin/jsx --extension jsx --no-cache-dir src/ js/`
    npm ERR! spawn ENOENT
    npm ERR! 
    npm ERR! Failed at the react-sortable-table@0.1.0 install script 'node_modules/react-tools/bin/jsx --extension jsx --no-cache-dir src/ js/'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the react-sortable-table package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node_modules/react-tools/bin/jsx --extension jsx --no-cache-dir src/ js/
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs react-sortable-table
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls react-sortable-table
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /some/dir/npm-debug.log

**Comment by haf** [comment]
Did you fix it?

**Comment by Rudolph-Miller** [comment]
@abejfehr 
@haf 

I've released version 1.0.0 ( no API changes, just released. :) ) , and it's now installable.
