### ISSUE TITLE
Custom class for th/td

### ISSUE THREAD

**Issue by np** [Rudolph-Miller/react-sortable-table#9]
While there is a way to customize the style using `dataStyle` and `headerStyle` there is no way to customize the class.

I'm proposing to either add `dataClass` and `headerClass`, or something more general such as `dataProps` and `headerProps`.

**Comment by Rudolph-Miller** [comment]
I added `headerProps` and `dataProps` via https://github.com/Rudolph-Miller/react-sortable-table/commit/bedf87defdbd6ea9f7c1db1975c4bcad0a0d02bb, and published new version `1.3.0`.

Try this APIs and please close this issue if it satisfied you. :)

**Comment by np** [comment]
Thanks it works great!
